//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Configurations
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Конфигурационный справочник"
	/// </summary>
	public partial class ConfigurationsReferenceObject
	{
		
		internal ConfigurationsReferenceObject(ConfigurationsReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new ConfigurationsType Class
		{
			get
			{
				return ((ConfigurationsType)(base.Class));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Конфигурационный справочник"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("a6182065-1f7b-465d-9643-adfcf61a0fce");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Описание"
			/// </summary>
		   public static readonly Guid Description = new Guid("9912cab6-adc6-42d1-8e9b-e4ff0a3c689a");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Значение"
			/// </summary>
		   public static readonly Guid ValueBool = new Guid("d403fd87-f975-424f-8c33-5fd45727bfc3");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Значение"
			/// </summary>
		   public static readonly Guid ValueString = new Guid("63340008-c691-4389-9225-ab639dbb6bef");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Значение"
			/// </summary>
		   public static readonly Guid ValueNumber = new Guid("3954493c-2104-44d2-8094-efad929d6327");

		}
	}
}
