//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Configurations
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект "Логический" справочника "Конфигурационный справочник" или порождённый от него
	/// </summary>
	public partial class BoolReferenceObject
	{
		
		internal BoolReferenceObject(ConfigurationsReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает параметр "Значение"
		/// </summary>
		public BooleanParameter ValueBool
		{
			get
			{
				return ((BooleanParameter)(this[FieldKeys.ValueBool]));
			}
		}
	}
}
