//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.Configurations
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет описание типа объекта справочника "Конфигурационный справочник"
	/// </summary>
	public partial class ConfigurationsType
	{
		
		internal ConfigurationsType(ConfigurationsTypes owner) : 
				base(owner)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Конфигурационный справочник"
		/// </summary>
		public new ConfigurationsTypes Classes
		{
			get
			{
				return ((ConfigurationsTypes)(base.Classes));
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Данные" или порождён от него
		/// </summary>
		public bool IsData
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Data);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Массив" или порождён от него
		/// </summary>
		public bool IsArray
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Array);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Параметр" или порождён от него
		/// </summary>
		public bool IsParameter
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Parameter);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Логический" или порождён от него
		/// </summary>
		public bool IsBool
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Bool);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Строка" или порождён от него
		/// </summary>
		public bool IsString
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.String);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Число" или порождён от него
		/// </summary>
		public bool IsNumber
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Number);
			}
		}
		
		/// <summary>
		/// Возвращает true, если текущий экземпляр описывает тип "Конфигурация" или порождён от него
		/// </summary>
		public bool IsConfig
		{
			get
			{
				return IsInherit(ConfigurationsTypes.Keys.Config);
			}
		}
	}
}
