//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypesConvertableObjectsNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.References.Links;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model.Parameters;
	
	
	/// <summary>
	/// Представляет объект справочника "Типы конвертируемых объектов ЭСИ"
	/// </summary>
	public partial class TypesConvertableObjectsNomenclatureReferenceObject
	{
		
		internal TypesConvertableObjectsNomenclatureReferenceObject(TypesConvertableObjectsNomenclatureReference reference) : 
				base(reference)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объекта
		/// </summary>
		public new TypesConvertableObjectsNomenclatureType Class
		{
			get
			{
				return ((TypesConvertableObjectsNomenclatureType)(base.Class));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Наименование"
		/// </summary>
		public StringParameter Name
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.Name]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Идентификатор типа"
		/// </summary>
		public GuidParameter ClassGuid
		{
			get
			{
				return ((GuidParameter)(this[FieldKeys.ClassGuid]));
			}
		}
		
		/// <summary>
		/// Возвращает параметр "Путь файла прототипа"
		/// </summary>
		public StringParameter PathPrototypeFile
		{
			get
			{
				return ((StringParameter)(this[FieldKeys.PathPrototypeFile]));
			}
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) параметров справочника "Типы конвертируемых объектов ЭСИ"
		/// </summary>
		public class FieldKeys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Наименование"
			/// </summary>
		   public static readonly Guid Name = new Guid("2e524fbd-8474-4dcc-90f1-a00472e36fed");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Идентификатор типа"
			/// </summary>
		   public static readonly Guid ClassGuid = new Guid("44bf14f7-4672-4336-bc61-759a8ace5908");

			/// <summary>
			/// Представляет уникальный идентификатор (GUID) параметра "Путь файла прототипа"
			/// </summary>
		   public static readonly Guid PathPrototypeFile = new Guid("ab01fced-ab5e-4ccd-9417-8d6d6b1d2889");

		}
	}
}
