//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypesConvertableObjectsNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	using TFlex.DOCs.Model;
	
	
	/// <summary>
	/// Представляет описание справочника "Типы конвертируемых объектов ЭСИ"
	/// </summary>
	public partial class TypesConvertableObjectsNomenclatureReference
	{
		
		/// <summary>
		/// Представляет уникальный идентификатор (GUID) справочника "Типы конвертируемых объектов ЭСИ"
		/// </summary>
		public static readonly System.Guid ReferenceId = new Guid("fcf00da8-06aa-4c57-86a9-522ef0a752b0");
		
		/// <summary>
		/// Инициализирует новый экземпляр TypesConvertableObjectsNomenclatureReference для работы с объектами справочника "Типы конвертируемых объектов ЭСИ"
		/// </summary>
		public TypesConvertableObjectsNomenclatureReference(TFlex.DOCs.Model.ServerConnection connection) : 
				base(connection, TypesConvertableObjectsNomenclatureReference.ReferenceId)
		{
		}
		
		private TypesConvertableObjectsNomenclatureReference(ParameterGroup masterGroup) : 
				base(masterGroup)
		{
		}
		
		/// <summary>
		/// Возвращает типы объектов справочника "Типы конвертируемых объектов ЭСИ"
		/// </summary>
		public new TypesConvertableObjectsNomenclatureTypes Classes
		{
			get
			{
				return ((TypesConvertableObjectsNomenclatureTypes)(base.Classes));
			}
		}
		
		protected override TypesConvertableObjectsNomenclatureReferenceObject CreateReferenceObjectForClass(ClassObject classObject)
		{
			TypesConvertableObjectsNomenclatureType type = classObject as TypesConvertableObjectsNomenclatureType;
			if ((type == null))
			{
				return null;
			}
			if (type.IsTypesConvertableObjectsNomenclatureReferenceObject)
			{
				return new TypesConvertableObjectsNomenclatureReferenceObject(this);
			}
			return new TypesConvertableObjectsNomenclatureReferenceObject(this);
		}
		
		public partial class Factory : SpecialReferenceFactory<TypesConvertableObjectsNomenclatureReference, TypesConvertableObjectsNomenclatureTypes>
		{
			
			internal Factory()
			{
			}
			
			public override TypesConvertableObjectsNomenclatureReference CreateReference(ParameterGroup masterGroup)
			{
				return new TypesConvertableObjectsNomenclatureReference(masterGroup);
			}
			
			public override TypesConvertableObjectsNomenclatureTypes CreateClassTree(ParameterGroup masterGroup)
			{
				return new TypesConvertableObjectsNomenclatureTypes(masterGroup);
			}
		}
	}
}
