//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFlex.DOCs.References.TypesConvertableObjectsNomenclature
{
	using System;
	using TFlex.DOCs.Model.References;
	using TFlex.DOCs.Model.Structure;
	using TFlex.DOCs.Model.Classes;
	
	
	/// <summary>
	/// Представляет типы объектов справочника "Типы конвертируемых объектов ЭСИ"
	/// </summary>
	public partial class TypesConvertableObjectsNomenclatureTypes
	{
		
		internal TypesConvertableObjectsNomenclatureTypes(ParameterGroup group) : 
				base(group)
		{
		}
		
		/// <summary>
		/// Возвращает описание типа объектов "Тип конвертируемого объекта ЭСИ"
		/// </summary>
		public TypesConvertableObjectsNomenclatureType TypesConvertableObjectsNomenclatureReferenceObject
		{
			get
			{
				return Find(Keys.TypesConvertableObjectsNomenclatureReferenceObject);
			}
		}
		
		protected override TypesConvertableObjectsNomenclatureType CreateClassObject(Guid classGuid)
		{
			return new TypesConvertableObjectsNomenclatureType(this);
		}
		
		/// <summary>
		/// Уникальные идентификаторы (GUID) типов объектов справочника "Типы конвертируемых объектов ЭСИ"
		/// </summary>
		public class Keys
		{
			
			/// <summary>
			/// Представляет уникальный идентификатор (GUID) типа "Тип конвертируемого объекта ЭСИ"
			/// </summary>
		   public static readonly Guid TypesConvertableObjectsNomenclatureReferenceObject = new Guid("237c4be7-91b5-4417-a39d-02e9fef935e8");

		}
	}
}
